import "server-only";

export type AutonomousDevelopmentPromptMode =
  | "EXPLICIT_TARGET_PATCH"
  | "PLANNED_PATCH";

export type AutonomousDevelopmentPromptInput = {
  objective: string;
  targetPaths: string[];
  mode: AutonomousDevelopmentPromptMode;
};

const MAX_OBJECTIVE_LENGTH = 4000;

function normalizePath(value: string) {
  return value
    .trim()
    .replace(/^\/+/, "")
    .replace(/\\+/g, "/");
}

function uniquePaths(paths: string[]) {
  return Array.from(
    new Set(
      paths
        .map(normalizePath)
        .filter(Boolean),
    ),
  );
}

export function extractExplicitRepositoryPaths(
  objective: string,
) {
  const normalizedObjective =
    objective
      .slice(0, MAX_OBJECTIVE_LENGTH)
      .replace(/[`"'“”‘’]/g, " ");

  const matches =
    normalizedObjective.match(
      /\b(?:app|components|docs|lib|scripts|tests|test|public|styles)\/[A-Za-z0-9._@\/+-]+/g,
    ) ?? [];

  return uniquePaths(
    matches.map((value) =>
      value.replace(
        /[.,;:!?)}\]]+$/g,
        "",
      ),
    ),
  );
}

export function buildAutonomousDevelopmentPrompt(
  input: AutonomousDevelopmentPromptInput,
) {
  const objective =
    input.objective
      .trim()
      .slice(
        0,
        MAX_OBJECTIVE_LENGTH,
      );

  const targetPaths =
    uniquePaths(
      input.targetPaths,
    );

  const targetText =
    targetPaths.length > 0
      ? targetPaths.join(", ")
      : "AIOS must determine the smallest valid target files from the real repository.";

  const modeText =
    input.mode ===
    "EXPLICIT_TARGET_PATCH"
      ? [
          "The user objective contains explicit repository paths.",
          "Treat those paths as the primary execution boundary.",
          "Do not perform recursive repository discovery.",
          "Do not call the LLM planner to rediscover an already explicit target.",
          "Read the exact target file(s) from the real GitHub repository.",
        ].join("\n")
      : [
          "The user objective does not contain a complete explicit target path.",
          "Use the real repository index and the existing planner only to determine the smallest valid target set.",
          "Never invent repository paths.",
        ].join("\n");

  return [
    "AIOS DEVELOPMENT PROMPT",
    "",
    "ROLE",
    "You are the internal development planner generated by AIOS.",
    "You are not the final code writer.",
    "Your purpose is to convert the Founder Objective into a safe executable development contract.",
    "",
    "FOUNDER OBJECTIVE",
    objective,
    "",
    "EXECUTION MODE",
    input.mode,
    "",
    "TARGET PATHS",
    targetText,
    "",
    "TARGET RESOLUTION RULES",
    modeText,
    "",
    "DEVELOPMENT CONTRACT",
    "1. Read the current real source before changing anything.",
    "2. Never regenerate an entire large source file when a precise patch is sufficient.",
    "3. Generate minimal SEARCH/REPLACE operations against the exact current source.",
    "4. SEARCH text must come from the current real file and must be unique.",
    "5. Preserve existing APIs, data interfaces, types, routes, state logic, permissions, and unrelated functionality.",
    "6. Do not modify files outside the resolved target set.",
    "7. Do not add dependencies unless the Founder Objective explicitly requires them and the existing architecture cannot satisfy the objective.",
    "8. Keep the implementation compatible with the existing Next.js application and WorkspaceShell/design system.",
    "9. Validate the final source before GitHub write.",
    "10. Run the existing GitHub readback and Vercel production build verification after writing.",
    "11. If Vercel reports a build failure, repair the smallest affected target using another exact patch.",
    "12. Stop and block instead of inventing files, APIs, credentials, permissions, or unsupported capabilities.",
    "",
    "PATCH CONTRACT",
    "The code-generation stage must return only AIOS_PATCH_BEGIN / AIOS_PATCH_END blocks.",
    "Do not return a complete file.",
    "Do not return a Markdown diff.",
    "Do not return placeholders, TODOs, ellipses, or omitted sections.",
    "",
    "SAFETY CONTRACT",
    "All GitHub writes remain inside the Founder-authorized repository and main branch.",
    "The final source must pass the existing Founder development safety contract.",
    "",
    "VERIFICATION CONTRACT",
    "GitHub write -> GitHub readback -> Vercel production build -> repair if necessary.",
  ].join("\n");
}
